name: unet
channels:
  - defaults
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
  - conda-forge
dependencies:
  - _tflow_select=2.1.0=gpu
  - absl-py=0.13.0=py37haa95532_0
  - aiohttp=3.7.4.post0=py37h2bbff1b_2
  - argcomplete=1.12.3=pyhd3eb1b0_0
  - astor=0.8.1=py37haa95532_0
  - async-timeout=3.0.1=py37haa95532_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blinker=1.4=py37haa95532_0
  - brotlipy=0.7.0=py37h2bbff1b_1003
  - ca-certificates=2021.10.26=haa95532_2
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2021.10.8=py37haa95532_0
  - cffi=1.14.6=py37h2bbff1b_0
  - chardet=4.0.0=py37haa95532_1003
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.3=pyhd3eb1b0_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - coverage=5.5=py37h2bbff1b_2
  - cryptography=3.4.8=py37h71e12ea_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.5=cuda10.0_0
  - cython=0.29.24=py37hd77b12b_0
  - debugpy=1.4.1=py37hd77b12b_0
  - decorator=5.1.0=pyhd3eb1b0_0
  - entrypoints=0.3=py37_0
  - gast=0.2.2=py37_0
  - google-auth=1.33.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - grpcio=1.36.1=py37hc60d5dd_1
  - h5py=2.8.0=py37hf7173ca_2
  - hdf5=1.8.20=hac2f561_1
  - icc_rt=2019.0.0=h0cc432a_1
  - idna=3.2=pyhd3eb1b0_0
  - importlib-metadata=4.8.1=py37haa95532_0
  - importlib_metadata=4.8.1=hd3eb1b0_0
  - intel-openmp=2021.3.0=haa95532_3372
  - ipykernel=6.4.1=py37haa95532_1
  - ipython=7.27.0=py37hd4e2768_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.0=py37haa95532_1
  - jpeg=9d=h2bbff1b_0
  - jupyter_client=7.0.1=pyhd3eb1b0_0
  - jupyter_core=4.8.1=py37haa95532_0
  - keras=2.3.1=0
  - keras-applications=1.0.8=py_1
  - keras-base=2.3.1=py37_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - libopencv=3.4.2=h20b85fd_0
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.17.2=h23ce68f_1
  - libtiff=4.2.0=hd0e1b90_0
  - lz4-c=1.9.3=h2bbff1b_1
  - markdown=3.3.4=py37haa95532_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mkl=2021.3.0=haa95532_524
  - mkl-service=2.4.0=py37h2bbff1b_0
  - mkl_fft=1.3.1=py37h277e83a_0
  - mkl_random=1.2.2=py37hf11a4ad_0
  - multidict=5.1.0=py37h2bbff1b_2
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - oauthlib=3.1.1=pyhd3eb1b0_0
  - opencv=3.4.2=py37h40b0b35_0
  - openssl=1.1.1l=h2bbff1b_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - parso=0.8.2=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.2.4=py37haa95532_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - protobuf=3.17.2=py37hd77b12b_0
  - py-opencv=3.4.2=py37hc319ecb_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.20=py_2
  - pygments=2.10.0=pyhd3eb1b0_0
  - pyjwt=2.1.0=py37haa95532_0
  - pyopenssl=21.0.0=pyhd3eb1b0_1
  - pysocks=1.7.1=py37_1
  - python=3.7.11=h6244533_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pywin32=228=py37hbaba5e8_1
  - pyyaml=5.4.1=py37h2bbff1b_1
  - pyzmq=22.2.1=py37hd77b12b_1
  - requests=2.26.0=pyhd3eb1b0_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scipy=1.7.1=py37hbe87c03_2
  - setuptools=58.0.4=py37haa95532_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=h2bbff1b_0
  - tensorboard=1.14.0=py37he3c9ec2_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=1.14.0=gpu_py37h5512b17_0
  - tensorflow-base=1.14.0=gpu_py37h55fc52a_0
  - tensorflow-estimator=1.14.0=py_0
  - tensorflow-gpu=1.14.0=h0d30ee6_0
  - termcolor=1.1.0=py37haa95532_1
  - tornado=6.1=py37h2bbff1b_0
  - traitlets=5.1.0=pyhd3eb1b0_0
  - typing-extensions=3.10.0.2=hd3eb1b0_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - urllib3=1.26.7=pyhd3eb1b0_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - werkzeug=0.16.1=py_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - win_inet_pton=1.1.0=py37haa95532_0
  - wincertstore=0.2=py37haa95532_2
  - wrapt=1.12.1=py37he774522_1
  - xz=5.2.5=h62dcd97_0
  - yaml=0.2.5=he774522_0
  - yarl=1.6.3=py37h2bbff1b_0
  - zipp=3.6.0=pyhd3eb1b0_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.4.9=h19a0ad4_0
  - pip:
      - numpy==1.21.6
      - packaging==23.0
      - pandas==1.3.5
      - pytz==2024.1
prefix: C:\Users\USER\anaconda3\envs\unet
